# Basic
title: åŒ–é£
subtitle: æ²‰ç¨³å¤§æ°” ç¬ƒè¡Œå…‹å·±
description: æ¬¢è¿æ¥åˆ°åŒ–é£çš„ä¸ªäººåšå®¢
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: åŒ– é£
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: å‰ç«¯ / PHP
url: "http://xinchanghao.github.io"

# Comment
comment:
    disqus: huafeng

# Social
social:
    #weibo: 5366874726
    github: xinchanghao
    twitter: xinchanghao
    mail: chh.xin@gmail.com

# ç™¾åº¦ç»Ÿè®¡
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
baidu:
    id: 46b9471b9f2035075f2e22f64055d7ab

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
ga:
    id: UA-118703487-1
    host: auto


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/xinchanghao/xinchanghao.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: åˆ—è¡¨, description: archive, url: '/archive'}
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}
    - {title: å…³äºæˆ‘, description: about, url: '/about'}


# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"
